version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.18
    commands:
      - echo "Installing dependencies... (NodeJs 18.18)"
  pre_build:
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install
  build:
    commands:
      - echo "Zipping deployment package..."      
      - zip -r9 ./zipped_source.zip .
  post_build:
    commands:
      - echo "Updating lambda Function... (ls -lap for testing purpose)"
      - ls -lap
      - aws lambda update-function-code --function-name aws-lambda-codeBuild-test --zip-file fileb://zipped_source.zip
      - echo "Well DONE!"